[project]
name = "pandas-gpt"
description = "Power up your data science workflow with ChatGPT"
version = "0.1.0"
authors = [
    { name = "Ryan Vandersmith" }
]
readme = "README.md"
dependencies = [
    "openai",
    "pandas"
]

[tool.setuptools]
packages = ["pandas_gpt"]
